# Packages

In [ ]:
%%capture
!pip install pip3-autoremove
!pip-autoremove torch torchvision torchaudio -y
!pip install torch torchvision torchaudio xformers --index-url https://download.pytorch.org/whl/cu121
!pip install unsloth
# Also get the latest nightly Unsloth!
!pip uninstall unsloth -y && pip install --upgrade --no-cache-dir --no-deps git+https://github.com/unslothai/unsloth.git
!pip install --upgrade --no-cache-dir transformers

# Load data

In [ ]:
import json

with open('/content/drive/MyDrive/stigma_project/final experiment results/test_data.json', 'r') as f:
  test_data = json.loads(f.read())
  f.close()

# With Type

In [ ]:
def format_wtype_message(title, post_text):
    message = [
        {
            "role": "system",
            "content": (
                "You are an expert in analyzing social media content for diabetes-related stigma.\n\n"
                "Your task is to classify the presence and type of stigma in a given social media post.\n\n"
                "Classification steps:\n"
                "1. Determine if the post expresses stigma:\n"
                "   - Yes stigma: Contains stigmatizing content or implications.\n"
                "   - No stigma: Neutral, supportive, or stigma-free.\n\n"
                "2. If 'Yes stigma', identify all applicable types:\n"
                "   - Experienced: Direct discrimination or exclusion due to diabetes.\n"
                "   - Perceived: Awareness or assumption that others hold negative views.\n"
                "   - Anticipated: Fear or expectation of being stigmatized.\n"
                "   - Internalized: Shame or self-blame from negative diabetes stereotypes.\n"
                "   - Intersectional: Stigma compounded by other factors (e.g., obesity, race).\n\n"
                "   If 'No stigma', return an empty list for Type.\n\n"
                "3. Provide a brief explanation (max 50 words) for your decision.\n\n"
                "Respond in this exact format:\n"
                "Label: [Yes stigma / No stigma]\n"
                "Type: [List of applicable types or []]\n"
                "Reasoning: [Your explanation]"
            )
        },
        {
            "role": "user",
            "content": (
                f"Text: {title} {post_text}\n\n"
                "Analyze the post for diabetes-related stigma."
            )
        }
    ]

    return message


all_messages = [format_wtype_message(d['title'], d['post text']) for d in test_data]

## Base Llama 3.2

In [ ]:
from unsloth import FastLanguageModel
import torch
max_seq_length = 1024 # Choose any! We auto support RoPE Scaling internally!
dtype = None # None for auto detection. Float16 for Tesla T4, V100, Bfloat16 for Ampere+
load_in_4bit = True # Use 4bit quantization to reduce memory usage. Can be False.

# 4bit pre quantized models we support for 4x faster downloading + no OOMs.
fourbit_models = [
    "unsloth/Meta-Llama-3.1-8B-bnb-4bit",      # Llama-3.1 2x faster
    "unsloth/Meta-Llama-3.1-8B-Instruct-bnb-4bit",
    "unsloth/Meta-Llama-3.1-70B-bnb-4bit",
    "unsloth/Meta-Llama-3.1-405B-bnb-4bit",    # 4bit for 405b!
    "unsloth/Mistral-Small-Instruct-2409",     # Mistral 22b 2x faster!
    "unsloth/mistral-7b-instruct-v0.3-bnb-4bit",
    "unsloth/Phi-3.5-mini-instruct",           # Phi-3.5 2x faster!
    "unsloth/Phi-3-medium-4k-instruct",
    "unsloth/gemma-2-9b-bnb-4bit",
    "unsloth/gemma-2-27b-bnb-4bit",            # Gemma 2x faster!

    "unsloth/Llama-3.2-1B-bnb-4bit",           # NEW! Llama 3.2 models
    "unsloth/Llama-3.2-1B-Instruct-bnb-4bit",
    "unsloth/Llama-3.2-3B-bnb-4bit",
    "unsloth/Llama-3.2-3B-Instruct-bnb-4bit",

    "unsloth/Llama-3.3-70B-Instruct-bnb-4bit" # NEW! Llama 3.3 70B!
] # More models at https://huggingface.co/unsloth

model, tokenizer = FastLanguageModel.from_pretrained(
    model_name = "unsloth/Llama-3.2-3B-Instruct", # or choose "unsloth/Llama-3.2-1B-Instruct"
    max_seq_length = max_seq_length,
    dtype = dtype,
    load_in_4bit = load_in_4bit,
    # token = "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", # use one if using gated models like meta-llama/Llama-2-7b-hf
)

==((====))==  Unsloth 2025.8.9: Fast Llama patching. Transformers: 4.55.3.
   \\   /|    Tesla T4. Num GPUs = 1. Max memory: 14.741 GB. Platform: Linux.
O^O/ \_/ \    Torch: 2.5.1+cu121. CUDA: 7.5. CUDA Toolkit: 12.1. Triton: 3.1.0
\        /    Bfloat16 = FALSE. FA [Xformers = 0.0.29.post1. FA2 = False]
 "-____-"     Free license: http://github.com/unslothai/unsloth
Unsloth: Fast downloading is enabled - ignore downloading bars which are red colored!

In [ ]:
from unsloth.chat_templates import get_chat_template

tokenizer = get_chat_template(
    tokenizer,
    chat_template = "llama-3.1",
)
FastLanguageModel.for_inference(model) # Enable native 2x faster inference

LlamaForCausalLM(
  (model): LlamaModel(
    (embed_tokens): Embedding(128256, 3072, padding_idx=128004)
    (layers): ModuleList(
      (0): LlamaDecoderLayer(
        (self_attn): LlamaAttention(
          (q_proj): Linear4bit(in_features=3072, out_features=3072, bias=False)
          (k_proj): Linear4bit(in_features=3072, out_features=1024, bias=False)
          (v_proj): Linear4bit(in_features=3072, out_features=1024, bias=False)
          (o_proj): Linear4bit(in_features=3072, out_features=3072, bias=False)
          (rotary_emb): LlamaRotaryEmbedding()
        )
        (mlp): LlamaMLP(
          (gate_proj): Linear4bit(in_features=3072, out_features=8192, bias=False)
          (up_proj): Linear4bit(in_features=3072, out_features=8192, bias=False)
          (down_proj): Linear4bit(in_features=8192, out_features=3072, bias=False)
          (act_fn): SiLU()
        )
        (input_layernorm): LlamaRMSNorm((3072,), eps=1e-05)
        (post_attention_layernorm): LlamaRMSNorm((3072,), eps=1e-05)
      )
      (1): LlamaDecoderLayer(
        (self_attn): LlamaAttention(
          (q_proj): Linear4bit(in_features=3072, out_features=3072, bias=False)
          (k_proj): Linear4bit(in_features=3072, out_features=1024, bias=False)
          (v_proj): Linear4bit(in_features=3072, out_features=1024, bias=False)
          (o_proj): Linear4bit(in_features=3072, out_features=3072, bias=False)
          (rotary_emb): LlamaRotaryEmbedding()
        )
        (mlp): LlamaMLP(
          (gate_proj): Linear(in_features=3072, out_features=8192, bias=False)
          (up_proj): Linear(in_features=3072, out_features=8192, bias=False)
          (down_proj): Linear(in_features=8192, out_features=3072, bias=False)
          (act_fn): SiLU()
        )
        (input_layernorm): LlamaRMSNorm((3072,), eps=1e-05)
        (post_attention_layernorm): LlamaRMSNorm((3072,), eps=1e-05)
      )
      (2-27): 26 x LlamaDecoderLayer(
        (self_attn): LlamaAttention(
          (q_proj): Linear4bit(in_features=3072, out_features=3072, bias=False)
          (k_proj): Linear4bit(in_features=3072, out_features=1024, bias=False)
          (v_proj): Linear4bit(in_features=3072, out_features=1024, bias=False)
          (o_proj): Linear4bit(in_features=3072, out_features=3072, bias=False)
          (rotary_emb): LlamaRotaryEmbedding()
        )
        (mlp): LlamaMLP(
          (gate_proj): Linear4bit(in_features=3072, out_features=8192, bias=False)
          (up_proj): Linear4bit(in_features=3072, out_features=8192, bias=False)
          (down_proj): Linear4bit(in_features=8192, out_features=3072, bias=False)
          (act_fn): SiLU()
        )
        (input_layernorm): LlamaRMSNorm((3072,), eps=1e-05)
        (post_attention_layernorm): LlamaRMSNorm((3072,), eps=1e-05)
      )
    )
    (norm): LlamaRMSNorm((3072,), eps=1e-05)
    (rotary_emb): LlamaRotaryEmbedding()
  )
  (lm_head): Linear(in_features=3072, out_features=128256, bias=False)
)

In [ ]:
from tqdm import tqdm, trange

all_responses = []
for msg in tqdm(all_messages):
  prompt = tokenizer.apply_chat_template(
      msg,
      tokenize = False,
      add_generation_prompt = True, # Must add for generatio
      )
  inputs = tokenizer(prompt, return_tensors='pt').to('cuda')
  outputs = model.generate(**inputs, max_new_tokens = 64, use_cache = True,
                         temperature = 1.0, min_p = 0.5)
  response = tokenizer.batch_decode(outputs)
  all_responses.append(response[0].split('<|eot_id|><|start_header_id|>assistant<|end_header_id|>')[1].strip())

 14%|█▍        | 42/302 [02:07<16:55,  3.91s/it]Unsloth: Input IDs of shape torch.Size([1, 1269]) with length 1269 > the model's max sequence length of 1024.
We shall truncate it ourselves. It's imperative if you correct this issue first.
 94%|█████████▎| 283/302 [13:55<00:53,  2.83s/it]Unsloth: Input IDs of shape torch.Size([1, 1038]) with length 1038 > the model's max sequence length of 1024.
We shall truncate it ourselves. It's imperative if you correct this issue first.
100%|██████████| 302/302 [14:48<00:00,  2.94s/it]

In [ ]:
with open('/content/drive/MyDrive/stigma_project/Llama3.2_base_wtype_test_pred_data.json', 'w') as f:
  f.write(json.dumps(all_responses))
  f.close()

## simple tuned

In [ ]:
from unsloth import FastLanguageModel
import torch
max_seq_length = 1024 # Choose any! We auto support RoPE Scaling internally!
dtype = None # None for auto detection. Float16 for Tesla T4, V100, Bfloat16 for Ampere+
load_in_4bit = True # Use 4bit quantization to reduce memory usage. Can be False.

model, tokenizer = FastLanguageModel.from_pretrained(
    model_name = "haji80mr-uoft/Llama-tuned-Lora-merged-V3", # YOUR MODEL YOU USED FOR TRAINING
    max_seq_length = max_seq_length,
    dtype = dtype,
    load_in_4bit = load_in_4bit,
    token = ""
)

==((====))==  Unsloth 2025.8.9: Fast Llama patching. Transformers: 4.55.3.
   \\   /|    Tesla T4. Num GPUs = 1. Max memory: 14.741 GB. Platform: Linux.
O^O/ \_/ \    Torch: 2.5.1+cu121. CUDA: 7.5. CUDA Toolkit: 12.1. Triton: 3.1.0
\        /    Bfloat16 = FALSE. FA [Xformers = 0.0.29.post1. FA2 = False]
 "-____-"     Free license: http://github.com/unslothai/unsloth
Unsloth: Fast downloading is enabled - ignore downloading bars which are red colored!

Loading checkpoint shards:   0%|          | 0/2 [00:00<?, ?it/s]

In [ ]:
from tqdm import tqdm, trange

all_responses = []
for msg in tqdm(all_messages):
  prompt = tokenizer.apply_chat_template(
      msg,
      tokenize = False,
      add_generation_prompt = True, # Must add for generatio
      )
  inputs = tokenizer(prompt, return_tensors='pt').to('cuda')
  outputs = model.generate(**inputs, max_new_tokens = 64, use_cache = True,
                         temperature = 1.0, min_p = 0.5)
  response = tokenizer.batch_decode(outputs)
  all_responses.append(response[0].split('<|eot_id|><|start_header_id|>assistant<|end_header_id|>')[1].strip())

100%|██████████| 302/302 [14:01<00:00,  2.79s/it]

In [ ]:
len(all_responses)

302

In [ ]:
with open('/content/drive/MyDrive/stigma_project/Llama3.2_simple_tuned_wtype_test_pred_data.json', 'w') as f:
  f.write(json.dumps(all_responses))
  f.close()

## semi tuned

In [ ]:
from unsloth import FastLanguageModel
import torch
max_seq_length = 1024 # Choose any! We auto support RoPE Scaling internally!
dtype = None # None for auto detection. Float16 for Tesla T4, V100, Bfloat16 for Ampere+
load_in_4bit = True # Use 4bit quantization to reduce memory usage. Can be False.

model, tokenizer = FastLanguageModel.from_pretrained(
    model_name = "haji80mr-uoft/semi-wtype-Llama-tuned-Lora-merged-V0", # YOUR MODEL YOU USED FOR TRAINING
    max_seq_length = max_seq_length,
    dtype = dtype,
    load_in_4bit = load_in_4bit,
    token = ""
)

==((====))==  Unsloth 2025.8.9: Fast Llama patching. Transformers: 4.55.3.
   \\   /|    Tesla T4. Num GPUs = 1. Max memory: 14.741 GB. Platform: Linux.
O^O/ \_/ \    Torch: 2.5.1+cu121. CUDA: 7.5. CUDA Toolkit: 12.1. Triton: 3.1.0
\        /    Bfloat16 = FALSE. FA [Xformers = 0.0.29.post1. FA2 = False]
 "-____-"     Free license: http://github.com/unslothai/unsloth
Unsloth: Fast downloading is enabled - ignore downloading bars which are red colored!

Loading checkpoint shards:   0%|          | 0/2 [00:00<?, ?it/s]

In [ ]:
from tqdm import tqdm, trange

all_responses = []
for msg in tqdm(all_messages):
  prompt = tokenizer.apply_chat_template(
      msg,
      tokenize = False,
      add_generation_prompt = True, # Must add for generatio
      )
  inputs = tokenizer(prompt, return_tensors='pt').to('cuda')
  outputs = model.generate(**inputs, max_new_tokens = 64, use_cache = True,
                         temperature = 1.0, min_p = 0.5)
  response = tokenizer.batch_decode(outputs)
  all_responses.append(response[0].split('<|eot_id|><|start_header_id|>assistant<|end_header_id|>')[1].strip())

100%|██████████| 302/302 [13:48<00:00,  2.74s/it]

In [ ]:
with open('/content/drive/MyDrive/stigma_project/Llama3.2_semi_tuned_wtype_test_pred_data.json', 'w') as f:
  f.write(json.dumps(all_responses))
  f.close()

# Parsing

In [ ]:
import json

with open('/content/drive/MyDrive/stigma_project/semi-supervised results/Llama3.2_gpt_semi_tuned_wtype_test_pred_data.json', 'r') as f:
  pred_data = json.loads(f.read())
  f.close()

In [ ]:
preds = []

for i in range(len(pred_data)):
  r = pred_data[i]
  pred = {'label': None, 'types': None}
  r_parts = r.split('\n')

  try:
    pred['label'] = r_parts[0].split(':')[1].strip().lower()
    types_str = r_parts[1].split(':')[1].strip()
  except:
    print(i)
    preds.append(pred)
    continue

  types_str = r_parts[1].split(':')[1].strip()
  types_str = types_str.replace('[', '').replace(']', '')
  if types_str == '':
    ans = []
  else:
    ans = [x.strip().lower().replace('\'', '') + ' stigma' for x in types_str.split(',')]
    # ans = [x.strip().lower().replace('\'', '') for x in types_str.split(',')]

  pred['types'] = ans
  preds.append(pred)

42
283

In [ ]:
with open('/content/drive/MyDrive/stigma_project/semi-supervised results/gpt_semi_tuned_wtype_test_pred.json', 'w') as f:
  f.write(json.dumps(preds))
  f.close()

# Get final result sheets

In [ ]:
import json
from tqdm import tqdm, trange
import pandas as pd
import sklearn
from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    balanced_accuracy_score
)

import numpy as np

In [ ]:
def jaccard_score(true_list, pred_list):
  assert len(true_list) == len(pred_list)

  scores = []
  for i in range(len(true_list)):
    if len(true_list[i]) == 0 and len(pred_list[i]) == 0:
      scores.append(0)
    else:
      true_set = set(true_list[i])
      pred_set = set(pred_list[i])
      j_score = len(true_set.intersection(pred_set)) / len(true_set.union(pred_set))
      scores.append(j_score)

  return np.mean(scores).item()

def binary_evaluate(true_label, pred_label, pos_label=1, neg_label=0):
    metrics = {
        'Accuracy':           accuracy_score(true_label, pred_label),
        'Macro Precision':    precision_score(true_label, pred_label, average='macro'),
        'Micro Precision':    precision_score(true_label, pred_label, average='micro'),
        'Macro Recall':       recall_score(true_label, pred_label, average='macro'),
        'Micro Recall':       recall_score(true_label, pred_label, average='micro'),
        'Macro F1':           f1_score(true_label, pred_label, average='macro'),
        'Micro F1':           f1_score(true_label, pred_label, average='micro'),
        'Binary F1 for yes class':           f1_score(true_label, pred_label, average='binary', pos_label=pos_label),
        'Binary F1 for no class':           f1_score(true_label, pred_label, average='binary', pos_label=neg_label),
        'Weighted F1':           f1_score(true_label, pred_label, average='weighted'),
        'Balanced Accuracy':  balanced_accuracy_score(true_label, pred_label).item(),
    }

    keys_list = list(metrics.keys())   # preserves insertion order (Python 3.7+)
    return metrics, keys_list


def evaluate(true_label, pred_label, true_list, pred_list):
    metrics = {
        'Accuracy':           accuracy_score(true_label, pred_label),
        'Macro Precision':    precision_score(true_label, pred_label, average='macro'),
        'Micro Precision':    precision_score(true_label, pred_label, average='micro'),
        'Macro Recall':       recall_score(true_label, pred_label, average='macro'),
        'Micro Recall':       recall_score(true_label, pred_label, average='micro'),
        'Macro F1':           f1_score(true_label, pred_label, average='macro'),
        'Micro F1':           f1_score(true_label, pred_label, average='micro'),
        'Jaccard Score': jaccard_score(true_list, pred_list),
    }

    keys_list = list(metrics.keys())   # preserves insertion order (Python 3.7+)
    return metrics, keys_list

In [ ]:
test_df = pd.read_json('/content/drive/MyDrive/stigma_project/final experiment results/test_data.json')
test_df = test_df.drop([42, 283]).reset_index(drop=True)
test_df

,title,post text,label,types
0,Januvia and headaches,Apparently headache is a common side effect of...,no stigma,[]
1,So paranoid of complications that I’ve lost my...,My weight is dropping fast. I eat blueberries ...,yes stigma,[internalized stigma]
2,"Anyone else not able to eat a ""normal"" diabeti...",I know this disease is vastly different for ev...,no stigma,[]
3,T2 is confusing.,Is t2 caused by obesity? Does losing weight ma...,no stigma,[]
4,Understanding spikes,I know no spike is good but there will be spik...,no stigma,[]
...,...,...,...,...
295,"What is your experience with a CGM, continuous...",I'm interested in your personal experiences fr...,no stigma,[]
296,Glipizide furthest Hypo episode from taking it?,I’m trying to see what’s the furthest episode ...,no stigma,[]
297,Side benefits of cutting out carbs...,I noticed some interesting physiological chang...,no stigma,[]
298,Tattoos,I really want to get a tattoo soon but I’m sca...,no stigma,[]
299,Diagnosed 3 months ago.,A1C was 13.1 and my blood sugar at diagnostics...,no stigma,[]

In [ ]:
with open('/content/drive/MyDrive/stigma_project/semi-supervised results/gpt_semi_tuned_wtype_test_pred.json', 'r') as f:
  responses = json.loads(f.read())
  f.close()

In [ ]:
del responses[42]
del responses[282]

len(responses)

300

In [ ]:
pred_df = pd.DataFrame(responses)
pred_df

          label                                      types
0     no stigma                                         []
1    yes stigma  [anticipated stigma, internalized stigma]
2     no stigma                                         []
3     no stigma                                         []
4     no stigma                                         []
..          ...                                        ...
295   no stigma                                         []
296   no stigma                                         []
297   no stigma                                         []
298   no stigma                                         []
299   no stigma                                         []

[300 rows x 2 columns]

In [ ]:
pred_df['label'].unique()

array(['no stigma', 'yes stigma'], dtype=object)

In [ ]:
ans_df, _ = binary_evaluate(test_df['label'], pred_df['label'], pos_label='yes stigma', neg_label='no stigma')
ans_df

{'Accuracy': 0.9433333333333334,
 'Macro Precision': 0.843859649122807,
 'Micro Precision': 0.9433333333333334,
 'Macro Recall': 0.7219202898550725,
 'Micro Recall': 0.9433333333333334,
 'Macro F1': 0.7668997668997669,
 'Micro F1': 0.9433333333333334,
 'Binary F1 for yes class': 0.5641025641025641,
 'Binary F1 for no class': 0.9696969696969697,
 'Weighted F1': 0.9372494172494172,
 'Balanced Accuracy': 0.7219202898550725}

In [ ]:
ans_df = pd.DataFrame([ans_df])
ans_df.to_csv('gpt_semi_wtype.csv', index=False)

## type detection evaluation

In [ ]:
from sklearn.preprocessing import MultiLabelBinarizer

mlb = MultiLabelBinarizer()
label_1_hot = mlb.fit_transform(test_df['types'])
pred_label_1_hot = mlb.transform(pred_df['types'])

type_ans_df, _ = evaluate(label_1_hot, pred_label_1_hot, test_df['types'], pred_df['types'])
type_ans_df

/usr/local/lib/python3.12/dist-packages/sklearn/preprocessing/_label.py:909: UserWarning: unknown class(es) ['anticipated stigma'] will be ignored
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

{'Accuracy': 0.9266666666666666,
 'Macro Precision': 0.25,
 'Micro Precision': 0.5,
 'Macro Recall': 0.3,
 'Micro Recall': 0.35714285714285715,
 'Macro F1': 0.25925925925925924,
 'Micro F1': 0.4166666666666667,
 'Jaccard Score': 0.019444444444444445}

In [ ]:
type_ans_df = pd.DataFrame([type_ans_df])
type_ans_df.to_csv('gpt_semi_wtype_type.csv', index=False)